### PR TITLE
bump version to 3.1.0 for new development

### PR DESCRIPTION
**Pull request by zburke**

### CODE REVIEW

**Comment by MikeTaylor** [comment]
What is the value in doing this now? Why not wait until there _is_ some new development?

**Comment by zburke** [comment]
@MikeTaylor, like, say, #86?

**Comment by MikeTaylor** [comment]
Yeah, that kind of thing.

**Comment by zburke** [comment]
Or would you rather that #86 gets merged with a patch release bump that can be tagged on master instead of on a `b3.0` branch? Your call; LMK your preference.

**Comment by MikeTaylor** [comment]
No, I don't mind at all. You're the one doing the work, so do it in whatever way seems best to you. Thanks!

**Comment by zburke** [comment]
You know what? Imma just bump the patch in #86 since there is no other ongoing work. That way, nobody has to faff about with release branches. KISS.

**Comment by MikeTaylor** [comment]
Love you, too.

:-)

**Pull request closed without merging**
