### PR TITLE
UICR-124: Implement baseline keyboard shortcuts

### PR DESCRIPTION
**Pull request by Javokhir12**
## Purpose
- Implement baseline keyboard shortcuts

## Refs
- https://issues.folio.org/browse/UICR-124

### CODE REVIEW

**Review by MikeTaylor — COMMENTED** [review]
It's really nice to see this!

**Comment by Javokhir12** [comment]
> It's really nice to see this!

Hi @MikeTaylor . could you please review and merge

**Comment by MikeTaylor** [comment]
> > It's really nice to see this!
> 
> Hi @MikeTaylor . could you please review and merge

Sorry, no. I've never done any work at all with keyboard shortcuts, and am not competent to review your work.

**Comment by Javokhir12** [comment]
@IvanKryzhanovskyi, please have a look.

**Comment by IvanKryzhanovskyi** [comment]
@zburke, @doytch, could you please take a look and merge current updates into the ui-courses if everything ok?

**Review by NikitaSedyx — APPROVED** [review]

**Review by JohnC-80 — APPROVED** [review]
Looks good. I like the implementation of the utility handler.

**Comment by Javokhir12** [comment]
Hi @MikeTaylor. Could you merge because it's end of sprint and we need to close this ticket today. Thank you!

**Pull request merged**
