### PR TITLE
do not publish 'artifacts' to npm

### PR DESCRIPTION
**Pull request by zburke**
https://issues.folio.org/browse/STRIPES-865

### CODE REVIEW

**Review by MikeTaylor — APPROVED** [review]
This looks reasonable to me, but maybe we should get the thoughts of @ankitasen-ubmainz, who created these scripts?

**Comment by zburke** [comment]
@MikeTaylor , fair point, but this line is present in [other versions of the workflow files](https://github.com/folio-org/ui-receiving/pull/388/files) @ankitasen-ubmainz created in other repos. IOW, I think I'm more in the realm of "make all the UI repos act similarly" rather than "implement something new, radical, and previously unheard of".

**Comment by MikeTaylor** [comment]
OK, makes sense to me. Go for it!

**Comment by zburke** [comment]
@MikeTaylor , I'm happy to report that after some handiwork by Michal in stripes-cli this package now builds correctly. Locally, however, I could not get the tests to run successfully and in reviewing the logs in CI I noticed that it appears tests have not been running for some time due to a Cypress glitch:
```
webpack built 62ce88482c10ca922f4e in 18545ms
The cypress npm package is installed, but the Cypress binary is missing.

We expected the binary to be installed here: /home/runner/.cache/Cypress/6.9.1/Cypress/Cypress

Reasons it may be missing:

- You're caching 'node_modules' but are not caching this path: /home/runner/.cache/Cypress
- You ran 'npm install' at an earlier build step but did not persist: /home/runner/.cache/Cypress

Properly caching the binary will fix this error and avoid downloading and unzipping Cypress.

Alternatively, you can run 'cypress install' to download the binary again.

https://on.cypress.io/not-installed-ci-error

----------

Platform: linux (Ubuntu - 22.04)
Cypress Version: 6.9.1
Done in 21.33s.
webpack built 2ec4a2ad5a9c78d0ebad in 1686ms
```
Somehow, the exit code here is 0 so instead of admitting to catastrophic failure of the entire system, Cypress seems to be saying, "Well, we couldn't run any tests, so they couldn't fail, so everything's fine!" 😬 I see the same message in PR logs as far back as March, 2023. Logs before that have already been purged. 

Do you think we should wait to merge all PRs in this repo until that problem can be resolved or do you think we should go ahead and merge this one since it seems entirely unrelated?

**Comment by MikeTaylor** [comment]
Go ahead and merge.

**Pull request merged**
